name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: ["master"]

permissions:
  packages: write

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build the Docker image (arm64)
        run: |
          docker buildx build --platform linux/arm64 . \
            --file Dockerfile \
            --tag ghcr.io/benjithatfoxguy/alist-bot:latest \
            --push
